name: Bump Semver Action
description: Bump a semver version.

branding:
  icon: tag
  color: green

inputs:
  current-version:
    description: The current version. If not provided, the action will use the latest version in the repository.
  level:
    description: The level of the bump. (major|minor|patch)
    required: true
  force:
    description: Whether to force the tag creation.
    default: 'false'
  token:
    description: The GitHub token.
    default: ${{ github.token }}

outputs:
  new-version:
    description: The new version.

runs:
  using: node20
  main: dist/index.js
