name: Bump Semantic Version Action
description: Bump a semantic version.

branding:
  icon: tag
  color: green

inputs:
  current-version:
    description: The current version. If not provided, the action will use the latest version in the repository.
  level:
    description: The level of the bump. (major|minor|patch)
    required: true
  force:
    description: Whether to force the tag creation.
    default: 'false'
  initial-version:
    description: The version to be pushed when no tags exist yet.
    default: v0.0.1
  token:
    description: The GitHub token.
    default: ${{ github.token }}

outputs:
  current-version:
    description: The current version.
  new-version:
    description: The new version.

runs:
  using: node20
  main: dist/index.js
