name: Bump Semver Action
description: Bump a semver version.

branding:
  icon: tag
  color: green

inputs:
  current_version:
    description: The current version. If not provided, the action will use the latest version in the repository.
  level:
    description: The level of the bump. (major|minor|patch)
    required: true
  token:
    description: The GitHub token.
    default: ${{ github.token }}

outputs:
  new_version:
    description: The new version.

runs:
  using: node20
  main: dist/index.js
