name: Release

on:
  workflow_dispatch:
    inputs:
      current-version:
        description: The current version. If not provided, the action will use the latest version in the repository.
        type: string
      level:
        type: choice
        description: The level of the bump.
        options:
          - patch
          - minor
          - major
      force:
        type: boolean
        description: Whether to force the tag creation.
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        id: bump
        with:
          current-version: ${{ inputs.current-version }}
          level: ${{ inputs.level }}
          force: ${{ inputs.force }}

      - uses: koki-develop/major-version-sync@v1
        with:
          version: ${{ steps.bump.outputs.new-version }}
          token: ${{ github.token }}

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new-version }}
