name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: The level of the bump.
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
        id: bump
        with:
          level: ${{ inputs.level }}

      - uses: koki-develop/major-version-sync@b86eb31aef1c06d81f133799b35ace3c80ebdf0a # v1.2.0
        with:
          version: ${{ steps.bump.outputs.new-version }}
          token: ${{ github.token }}

      - name: Create release
        env:
          CURRENT_VERSION: ${{ steps.bump.outputs.current-version }}
          NEW_VERSION: ${{ steps.bump.outputs.new-version }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${NEW_VERSION}" \
            --repo "${GITHUB_REPOSITORY}" \
            --title "${NEW_VERSION}" \
            --generate-notes \
            --notes-start-tag "${CURRENT_VERSION}"
